### ISSUE TITLE
Color green if reviewed under GH's new Review process

### ISSUE THREAD

**Issue by mileszs** [dracco1993/GitHubUtils#8]
Now that GitHub has a fancy new official review process, it'd be sweet to also mark one green when the user has either approved or rejected the PR. 

Could possibly use this portion on the PR page itself, perhaps?

<img width="570" alt="screenshot 2017-01-06 12 40 17" src="https://cloud.githubusercontent.com/assets/2425/21727045/5083f81e-d40d-11e6-8338-60fc54e7ff94.png">

**Comment by dracco1993** [comment]
Added in 0edb3e24824eeda7ce61d365a524082f4859202c
